### ISSUE TITLE
FR: Warn about size before transfer and tar on cluster

### ISSUE THREAD

**Issue by srpomeroy** [AjayTripathy/etl-backup#1]
Working with a customer to download their ETL so we can test with it.
They suggested we include a warning about transfer size.
And also that we tar the files in the cluster before transfer.

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/etl-backup think you meant to file it here.

**Comment by srpomeroy** [comment]
I went to but issues are not enabled by default due to it being forked from this repo.

**Comment by AjayTripathy** [comment]
Oops, thanks. Enabled issues there and moved.
